config/routes.rb
ShowDontTellsEngine::Engine.routes.draw do
	resources :show_dont_tells
	resources :presentations
end

app/models/show_dont_tells_engine/presentation.rb
module ShowDontTellsEngine
  class Presentation < ActiveRecord::Base
    belongs_to :show_dont_tell
  end
end

app/models/show_dont_tells_engine/show_dont_tell.rb
module ShowDontTellsEngine
  class ShowDontTell < ActiveRecord::Base
    has_many :presentations

    validates :date, presence: true, uniqueness: true

    accepts_nested_attributes_for :presentations, allow_destroy: true
  end
end

app/controllers/show_dont_tells_engine/application_controller.rb
module ShowDontTellsEngine
  class ApplicationController < ::ApplicationController
    if Rails.env.test?
      layout 'dummy'
    else
      layout 'admin'
    end
  end
end

app/controllers/show_dont_tells_engine/presentations_controller.rb
require_dependency "show_dont_tells_engine/application_controller"

module ShowDontTellsEngine
  class PresentationsController < ApplicationController
    before_action :find_presentation, only: [:show, :edit, :update, :destroy]

    def index
      @presentations = Presentation.all
    end

    def show
    end

    def new
      @presentation = Presentation.new
    end

    def edit
    end

    def create
      @presentation = Presentation.new(presentation_params)
      if @presentation.save
        redirect_to @presentation, notice:
          'presentation was successfully created.'
      else
        render 'new'
      end
    end

    def update
      if @presentation.update(presentation_params)
        redirect_to @level, notice: 'presentation was successfully updated.'
      else
        render 'edit'
      end
    end

    def destroy
      @presentation.destroy
      redirect_to levels_url, notice: 'presentation was successfully destroyed.'
    end

    private

    def find_presentation
      @presentation = Presentation.find(params[:id])
    end

    def presentation_params
      params.require(:presentations).permit(:show_dont_tell_id,
        :title, :description, :user_id)
    end
  end
end

app/controllers/show_dont_tells_engine/show_dont_tells_controller.rb
require_dependency "show_dont_tells_engine/application_controller"

module ShowDontTellsEngine
  class ShowDontTellsController < ApplicationController
    before_action :find_show_dont_tell, only: [:show, :edit, :update, :destroy]

    def index
      @show_dont_tells = ShowDontTell.all
    end

    def show
    end

    def new
      @show_dont_tell = ShowDontTell.new
    end

    def edit
    end

    def create
      @show_dont_tell = ShowDontTell.new(show_dont_tell_params)
      if @show_dont_tell.save
        redirect_to show_dont_tells_url, notice: 'Show dont tell was successfully created.'
   else
        render :new
      end
    end

    def update
      if @show_dont_tell.update(show_dont_tell_params)
        redirect_to show_dont_tells_url, notice: 'Show dont tell was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @show_dont_tell.destroy
      redirect_to show_dont_tells_url, notice: 'Show dont tell was successfully destroyed.'
    end
    
    private

    def find_show_dont_tell
      @show_dont_tell = ShowDontTell.find(params[:id])
    end
    
    def show_dont_tell_params
      params.require(:show_dont_tell).permit(
        :date, presentations_attributes: [ :id,
        :title, :description, :user_id,
        :show_dont_tell_id, :_destroy
        ])
    end
  end
end

app/controllers/show_dont_tells_engine/workshops_controller.rb
require_dependency "show_dont_tells_engine/application_controller"

module ShowDontTellsEngine
  class ShowDontTellsController < ApplicationController
    before_action :find_show_dont_tell, only: [:show, :edit, :update, :destroy]

    def index
      @show_dont_tells = ShowDontTell.all
    end

    def show
    end

    def new
      @show_dont_tell = ShowDontTell.new
    end

    def edit
    end

    def create
      @show_dont_tell = ShowDontTell.new(show_dont_tell_params)
      if @show_dont_tell.save
        redirect_to show_dont_tells_url, notice: 'Show dont tell was successfully created.'
   else
        render :new
      end
    end

    def update
      if @show_dont_tell.update(show_dont_tell_params)
        redirect_to show_dont_tells_url, notice: 'Show dont tell was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @show_dont_tell.destroy
      redirect_to show_dont_tells_url, notice: 'Show dont tell was successfully destroyed.'
    end
    
    private

    def find_show_dont_tell
      @show_dont_tell = ShowDontTell.find(params[:id])
    end
    
    def show_dont_tell_params
      params.require(:show_dont_tell).permit(:title)
    end
  end
end

app/helpers/show_dont_tells_engine/application_helper.rb
module ShowDontTellsEngine
  module ApplicationHelper
    def method_missing method, *args, &block
      puts "LOOKING FOR ROUTES #{method}"
      if method.to_s.end_with?('_path') or method.to_s.end_with?('_url')
        if main_app.respond_to?(method)
          main_app.send(method, *args)
        else
          super
        end
      else
        super
      end
    end

    def respond_to?(method)
      if method.to_s.end_with?('_path') or method.to_s.end_with?('_url')
        if main_app.respond_to?(method)
          true
        else
          super
        end
      else
        super
      end
    end
  end
end

app/helpers/show_dont_tells_engine/show_dont_tells_helper.rb
module ShowDontTellsEngine
  module ShowDontTellsHelper
   
  end
end

app/views/layouts/show_dont_tells_engine/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShowDontTellsEngine</title>
  <%= stylesheet_link_tag    "show_dont_tells_engine/application", media: "all" %>
  <%= javascript_include_tag "show_dont_tells_engine/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/show_dont_tells_engine/show_dont_tells/_form.html.haml
= simple_form_for(@workshop, html: { multipart: true }) do |f|
  = render partial: 'shared/errors', locals: { resource: @workshop }
  .col-md-3
    .span3
  .col-md-6
    .span12
      .field
        = f.input :title
      .field
        = f.input :description
      .actions
        = link_to 'Cancel', workshops_path, class: 'btn btn-disabled'
        = f.submit 'Save', class: 'btn'
  .col-md-3
    .span3
  
.clearfix

app/views/show_dont_tells_engine/show_dont_tells/_show_dont_tell.html.haml
%tr
  %td= show_dont_tell.title
  %td= show_dont_tell.description
  %td= link_to 'Show', show_dont_tell
  %td= link_to 'Edit', edit_show_dont_tell_path(show_dont_tell)
  %td= link_to 'Destroy', show_dont_tell, method: :delete,
    data: { confirm: 'Are you sure?' }

app/views/show_dont_tells_engine/show_dont_tells/edit.html.haml
%h1 Editing Show dont tell
= render 'form'
= link_to 'Show', @show_dont_tell
|
= link_to 'Back', show_dont_tells_path

app/views/show_dont_tells_engine/show_dont_tells/index.html.haml
%h1 Listing Show dont tells
%table
  %thead
    %tr
      %th Name
      %th Description
      %th{ colspan: 3 }
    %tbody
      = render @show_dont_tell
%br
= link_to 'New show dont tell', new_show_dont_tell_path

app/views/show_dont_tells_engine/show_dont_tells/new.html.haml
%h1 New Show dont tell
= render 'form'
= link_to 'Back', show_dont_tells_path

app/views/show_dont_tells_engine/show_dont_tells/show.html.haml
%p#notice= notice
%p
  %strong Title:
  = @show_dont_tell.title
%p
  %strong Description:
  = @show_dont_tell.description
= link_to 'Edit', edit_show_dont_tell_path(@show_dont_tell)
|
= link_to 'Back', show_dont_tells_path